{
 "title": "Pyth Price Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "symbol",
    "query": {
     "query": "label_values(pyth_oracle_aggregated_price, pyth_symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_status{pyth_symbol=\"$symbol\"}"
    }
   ]
  },
  {
   "title": "Num Publishers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(pyth_oracle_publisher_status{pyth_symbol=\"$symbol\"} == 1) by (pyth_publisher))"
    }
   ]
  },
  {
   "title": "Latest Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=\"$symbol\"}"
    }
   ]
  },
  {
   "title": "Confidence",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "±" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_conf_amount{pyth_symbol=\"$symbol\"}"
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=\"$symbol\"}",
     "legendFormat": "Price"
    },
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=\"$symbol\"} + pyth_oracle_aggregated_conf_amount {pyth_symbol=\"$symbol\"}",
     "legendFormat": "Price Max"
    },
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=\"$symbol\"} - pyth_oracle_aggregated_conf_amount {pyth_symbol=\"$symbol\"}",
     "legendFormat": "Price Min"
    }
   ]
  },
  {
   "title": "Price Components",
   "type": "timeseries",
   "description": "Published Price by publisher key",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(\n    pyth_oracle_publisher_price{pyth_symbol=\"$symbol\"} > 0)\n    and (pyth_oracle_publisher_status{pyth_symbol=\"$symbol\"} == 1)\n    and (\n        (pyth_oracle_aggregated_slot{pyth_symbol=\"$symbol\"}\n        - on(pyth_symbol) group_right\n        pyth_oracle_publisher_slot{pyth_symbol=\"$symbol\"}\n    ) < 25\n)",
     "legendFormat": "{{pyth_publisher}}"
    }
   ]
  }
 ]
}