{
 "title": "Pyth Publisher Details",
 "time": { "from": "2022-03-09T15:37:34.085Z", "to": "2022-03-09T16:53:24.165Z" },
 "templating": {
  "list": [
   {
    "name": "publisher",
    "query": {
     "query": "label_values(pyth_oracle_publisher_price, pyth_publisher)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime Matrix",
   "type": "stat",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(pyth_oracle_publisher_status{pyth_publisher=\"$publisher\"}) by (pyth_symbol)",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(pyth_solana_publish_account_balance{pyth_publisher=\"$publisher\"} / 1e9)"
    }
   ]
  },
  {
   "title": "Exp. Daily Fee Spent",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-24 * (min(delta(pyth_solana_publish_account_balance{pyth_publisher=\"$publisher\"}[$__interval])) / 1000000000)"
    }
   ]
  },
  {
   "title": "Hourly SOL Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "-3600 * (min(deriv(pyth_solana_publish_account_balance{pyth_publisher=\"$publisher\"}[5m])) / 1000000000)",
     "legendFormat": "SOL Rate"
    }
   ]
  }
 ]
}