{
 "title": "Pyth Price Component Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "symbol",
    "query": {
     "query": "label_values(pyth_oracle_aggregated_price, pyth_symbol)"
    }
   },
   {
    "name": "publisher",
    "query": {
     "query": "label_values(pyth_oracle_publisher_price{pyth_symbol=\"$symbol\"}, pyth_publisher)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_publisher_status{pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"}"
    }
   ]
  },
  {
   "title": "Latest Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_publisher_price{pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"}"
    }
   ]
  },
  {
   "title": "Confidence",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "±" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_publisher_conf_amount{pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((max(clamp_max(pyth_oracle_publisher_status{pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"}, 1) or vector(0)))[1h:])"
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "pyth_oracle_publisher_price{pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"}",
     "legendFormat": "Price"
    },
    {
     "expr": "pyth_oracle_publisher_price{pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"} + pyth_oracle_publisher_conf_amount {pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"}",
     "legendFormat": "Price Max"
    },
    {
     "expr": "pyth_oracle_publisher_price{pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"} - pyth_oracle_publisher_conf_amount {pyth_symbol=\"$symbol\",pyth_publisher=\"$publisher\"}",
     "legendFormat": "Price Min"
    }
   ]
  }
 ]
}