{
 "title": "Pyth Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Publishers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Publishers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(rate(pyth_txs_total{tx_status=\"success\"}[15m])) by (pyth_publisher) > 0.1)"
    }
   ]
  },
  {
   "title": "Publisher Tx Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "sum(rate(pyth_txs_total[$__rate_interval])) by (tx_status)",
     "legendFormat": "{{tx_status}}"
    }
   ]
  },
  {
   "title": "Fee Reserves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min(pyth_solana_publish_account_balance) by (pyth_publisher)) / 1e9"
    }
   ]
  },
  { "title": "Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Crypto Prices",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=~\"Crypto.+/USD\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  {
   "title": "FX Prices",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=~\"FX.+/USD\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  {
   "title": "Equity Prices",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=~\"Equity.+/USD\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  {
   "title": "Metal Prices",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_price{pyth_symbol=~\"Metal.+/USD\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Crypto Status",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_status{pyth_symbol=~\"Crypto.+\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  {
   "title": "FX Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_status{pyth_symbol=~\"FX.+\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  {
   "title": "Equity Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_status{pyth_symbol=~\"Equity.+\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  },
  {
   "title": "Metal Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pyth_oracle_aggregated_status{pyth_symbol=~\"Metal.+\"}",
     "legendFormat": "{{ pyth_symbol }}"
    }
   ]
  }
 ]
}