apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: 8GpmMT-7z
    url: http://prometheus:9090
    version: 1
    editable: false
    isDefault: true
